### PR TITLE
V0.3

### PR DESCRIPTION
**Pull request by great-houk**
This branch has a lot of changes. The major ones are as follows:

1. Update design constraints to match what JLC advertises, and redesign accordingly
2. Rerouting of lines under BGA to prevent overlap. Might not have been necessary, but there's no harm in doing it
3. Remake USB footprint with different pin names to remove some annoying warnings
4. Change USB data line routing to get as close as possible to 90 ohms
5. Add ground planes to top and bottom layers, and VIAs to better stitch them
6. Match all components with corresponding LCSC parts so a BOM can be auto generated

The PCB schematic is basically unchanged. In this state, all the files JLC needs for manufacturing are basically complete, and there's only two more things to do: check over the part selections made for LCSC, as making errors there is easy and avoidable, and potentially adjust pick and place rotations/positions. However, JLC says they have engineers manually realign the pick and place stuff, so it should be ok in its current state.

### CODE REVIEW

**Comment by mriise** [comment]
can you rename to mention v0.3? dont want to confuse this with future branches that will _actually_ be production PRs

**Comment by mriise** [comment]
when ordering assembly with JLC you can make orientation adjustments before it gets sent off, and so far everything ive had assembled has been double checked by them :+1: nice not to worry about it though if its automatic.

**Comment by mriise** [comment]
FB selection C524454 (90Ω @ 100MHz) is has a pretty low impedance @ frequency  
image

Ideally we would want a stronger one like BLM18PG221SN1D, see `FB7`
image
 https://www.ti.com/lit/ug/slla312c/slla312c.pdf?ts=1668393503471


For now though we can run with C524454 (or even a 0 ohm resistor) since our cables are more consistent, but lets get it changed for next version. can you open an issue for this?

**Comment by mriise** [comment]
The currently selected inductor (C1034) has a saturation limit of 15mA which is way under what we need. 
we need a _much_ higher amperage than that (ref below) - at least 350mA.
https://community.nxp.com/t5/LPC-Microcontrollers/LPC55xx-DC-to-DC-converter/m-p/1331812/highlight/true#M46338

**Comment by mriise** [comment]
C145962 is... interesting? not sure if it will actually fit the connector we need but we can give it a shot... lol

**Comment by mriise** [comment]
no need to buy the 2mm pin header and have it placed IMO, they are standard and easy to get ahold of since arduinos and the like use them. Also relatively easy to hand solder (if needed at all). I mainly had these as a backup in case I was having issues with the other ones. Nothing simpler than soldering wires directly into a through hole.

**Comment by great-houk** [comment]
> C145962 is... interesting? not sure if it will actually fit the connector we need but we can give it a shot... lol

This is what the 3D model looks like, is there a connector on digikey or something that might work better?

**Comment by mriise** [comment]
> is there a connector on digikey or something that might work better?

https://www.digikey.com/en/products/detail/jst-sales-america-inc/BM05B-SRSS-TBT-LF-SN/1828499

this is the actual one by JST, though im fairly certain they don't work with JLCPCB... so yeah. although again this isn't terrible to hand solder on for now, we can do kitted things when production time actually comes around.

**Review by mriise — CHANGES_REQUESTED** [review]
see above comments

**Comment by mriise** [comment]
inductor is the major blocker here, we can replace FB with a 0ohm resistor and not place a switch connector just to get something together to start programming with.

**Comment by great-houk** [comment]
Ok, it should be good now!
Changes made:

- Find proper inductor
- Find better ferrite bead (600Ω @ 100mHz now)
- Remove C145962 from pick and place
- Replace what was supposed to be a fuse with a 0Ω resistor, it used to be a ferrite bead

**Review by mriise — APPROVED** [review]
<3

**Pull request merged**
